import Link from 'next/link'
/* eslint-disable @next/next/no-img-element -- supplier URLs are intentionally loaded directly; no image storage/optimizer proxy */
import { requireAdminPage } from '@/lib/auth/admin'
import { createProductEditService } from '@/modules/products/product-edit-factory'

export default async function ProductsPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}) {
  const user=await requireAdminPage(); const params=await searchParams
  const result=await createProductEditService().list(user.id,{search:params.search,filter:params.filter,sort:params.sort,page:Number(params.page)||1})
  return <main className="container wide"><div className="page-head"><div><h1>내 상품</h1><p>저장된 DB 정보만 조회하며 공급사 API를 호출하지 않습니다.</p></div><Link className="button" href="/admin/products/import">상품 가져오기</Link></div>
    <form className="toolbar"><input name="search" defaultValue={params.search} placeholder="상품명, 상품번호, 내부 ID 검색"/><select name="filter" defaultValue={params.filter??''}><option value="">전체</option><option value="draft">초안</option><option value="editing">편집 중</option><option value="ready">등록 준비 완료</option><option value="sold_out">품절 원본</option><option value="missing_price">가격 미입력</option><option value="missing_category">카테고리 미지정</option><option value="missing_image">이미지 없음</option><option value="option_review">옵션 검토 필요</option></select><select name="sort" defaultValue={params.sort??''}><option value="">최근 가져온 순</option><option value="updated">최근 수정 순</option><option value="cost">공급가</option><option value="price">판매가</option><option value="title">상품명</option></select><button>조회</button></form>
    <div className="table-wrap"><table><thead><tr><th>이미지</th><th>상품</th><th>공급처</th><th>공급가 / 판매가</th><th>원본 상태</th><th>편집 상태</th><th>마지막 수정 / 동기화</th></tr></thead><tbody>{result.items.map((item)=>{const image=item.selectedImages.find((i)=>i.enabled&&i.isPrimary)??item.selectedImages.find((i)=>i.enabled);return <tr key={item.id}><td>{image?<img className="thumb" src={image.storedUrl??image.sourceUrl} alt=""/>:'-'}</td><td><Link href={`/admin/products/${item.id}/edit`}><strong>{item.title||'(상품명 미입력)'}</strong></Link><small>{item.originalName}<br/>{item.externalProductId}<br/>{item.id}</small></td><td>{item.supplierName}</td><td>{item.supplierPrice??'-'} / {item.sellingPrice?.toLocaleString()??'-'} KRW</td><td>{item.availability}</td><td><span className={`badge ${item.status}`}>{item.status}</span></td><td>{format(item.updatedAt)}<br/>{format(item.lastSyncedAt)}</td></tr>})}</tbody></table></div>
    {!result.items.length&&<p className="card">조건에 맞는 상품이 없습니다.</p>}<nav className="pagination">{result.page>1&&<Link href={query(params,result.page-1)}>이전</Link>}<span>{result.page} / {Math.max(1,Math.ceil(result.total/result.pageSize))}</span>{result.page*result.pageSize<result.total&&<Link href={query(params,result.page+1)}>다음</Link>}</nav>
  </main>
}
function format(value:Date){return new Intl.DateTimeFormat('ko-KR',{dateStyle:'short',timeStyle:'short',timeZone:'Asia/Seoul'}).format(value)}
function query(params:Record<string,string|undefined>,page:number){const q=new URLSearchParams();for(const [k,v] of Object.entries(params))if(v)q.set(k,v);q.set('page',String(page));return `?${q}`}
